In [1]:
%run GpuOptions.ipynb

In [2]:
import glob
from common import frozenmodel
from common.classifier import Classifier
from common.image import crop
from PIL import Image

classifier = Classifier(model=frozenmodel.generate(), labels=frozenmodel.labels())

# TODO: maybe make this build a collage with the classifications
for (filepath, _) in zip(glob.iglob('*.jpg'), range(4)):
    image = Image.open(filepath)
    crop(image, x=832, y=442, width=224, height=224).show()
    print(classifier.classify(crop(image, x=832, y=442, width=224, height=224)))


(<Label.MYSTICAL: 'Mystical'>, <tf.Tensor: shape=(), dtype=float32, numpy=170.03952>)
(<Label.NOT_VISIBLE: 'NotVisible'>, <tf.Tensor: shape=(), dtype=float32, numpy=118.000374>)
(<Label.NOT_VISIBLE: 'NotVisible'>, <tf.Tensor: shape=(), dtype=float32, numpy=202.34541>)
(<Label.NOT_VISIBLE: 'NotVisible'>, <tf.Tensor: shape=(), dtype=float32, numpy=168.02611>)
